version: "3"

services:
  app:
    ports:
      - "81:8080"
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      DB_HOST: database

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: tasks17
      POSTGRES_PASSWORD: tasks17
