version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./database:/var/mysql
    environment:
      MYSQL_DATABASE: golang
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: >
      --sql-mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
